# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fzXk-mF7gq3Bj2cIiAsP4XYFoXWLF_J8
"""

import pandas as pd

# 1. EXTRAÇÃO (Extract)
# Imagine que você criou um arquivo 'usuarios.csv' com as colunas: Nome, Saldo
df = pd.read_csv('usuarios.csv')

# 2. TRANSFORMAÇÃO (Transform)
# Vamos criar uma mensagem personalizada para cada cliente
def gerar_mensagem(nome):
    return f"Olá {nome}, investir hoje é garantir o seu amanhã!"

df['Mensagem'] = df['Nome'].apply(gerar_mensagem)

# 3. CARREGAMENTO (Load)
# Salvamos o resultado em um novo arquivo
df.to_csv('clientes_com_mensagens.csv', index=False)
print("ETL concluído com sucesso!")